import type { Workflow, WorkflowState, WorkflowArtifact } from "./types.js";

/**
 * Generate an HTML report for a completed (or in-progress) workflow.
 */
export function generateReport(workflow: Workflow, state: WorkflowState): string {
	const now = Date.now();
	const duration = (state.completedAt || now) - state.startedAt;

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(workflow.name)} — Report</title>
<style>
${CSS}
</style>
</head>
<body>
<div class="report">
	<header class="report-header">
		<h1>${esc(workflow.name)}</h1>
		<div class="meta">
			<span class="badge badge-${state.status}">${state.status.toUpperCase()}</span>
			<span class="meta-item">Started: ${formatTime(state.startedAt)}</span>
			${state.completedAt ? `<span class="meta-item">Completed: ${formatTime(state.completedAt)}</span>` : ""}
			<span class="meta-item">Duration: ${formatDuration(duration)}</span>
		</div>
		<p class="description">${esc(workflow.description)}</p>
		${renderContext(state.context)}
	</header>

	<section class="phases">
		<h2>Phases</h2>
		${workflow.phases.map((phase, i) => renderPhase(phase, i, state)).join("\n")}
	</section>

	${state.artifacts.length > 0 ? renderArtifacts(state.artifacts) : ""}

	<footer class="report-footer">
		<p>Generated by Bobbit Workflow Engine at ${formatTime(now)}</p>
	</footer>
</div>
</body>
</html>`;
}

function renderContext(context: Record<string, string>): string {
	const entries = Object.entries(context);
	if (entries.length === 0) return "";
	return `
	<div class="context">
		<h3>Context</h3>
		<table class="context-table">
			${entries.map(([k, v]) => `<tr><td class="context-key">${esc(k)}</td><td class="context-value"><code>${esc(v)}</code></td></tr>`).join("\n")}
		</table>
	</div>`;
}

function renderPhase(
	phase: { id: string; name: string; exitCriteria: string },
	index: number,
	state: WorkflowState,
): string {
	// Find the most recent record for this phase
	const records = state.phaseHistory.filter((r) => r.phaseId === phase.id);
	const latest = records[records.length - 1];
	const isActive = state.currentPhaseIndex === index && state.status === "running";
	const status = isActive ? "active" : latest?.status || "pending";

	const phaseDuration =
		latest && latest.completedAt
			? formatDuration(latest.completedAt - latest.startedAt)
			: latest
				? formatDuration((Date.now()) - latest.startedAt) + " (ongoing)"
				: "—";

	const phaseArtifacts = state.artifacts.filter((a) => a.phaseId === phase.id);

	return `
	<div class="phase phase-${status}">
		<div class="phase-header">
			<span class="phase-icon">${statusIcon(status)}</span>
			<h3 class="phase-title">${esc(phase.name)}</h3>
			<span class="badge badge-sm badge-${status}">${status}</span>
			<span class="phase-duration">${phaseDuration}</span>
		</div>
		<div class="phase-body">
			<p class="exit-criteria"><strong>Exit criteria:</strong> ${esc(phase.exitCriteria)}</p>
			${phaseArtifacts.length > 0 ? renderPhaseArtifacts(phaseArtifacts) : ""}
		</div>
	</div>`;
}

function renderPhaseArtifacts(artifacts: WorkflowArtifact[]): string {
	return `
	<div class="phase-artifacts">
		<h4>Artifacts</h4>
		<ul>
			${artifacts.map((a) => `<li><code>${esc(a.name)}</code> <span class="artifact-meta">(${esc(a.mimeType)}, ${formatTime(a.collectedAt)})</span></li>`).join("\n")}
		</ul>
	</div>`;
}

function renderArtifacts(artifacts: WorkflowArtifact[]): string {
	return `
	<section class="artifacts">
		<h2>All Artifacts</h2>
		<table class="artifact-table">
			<thead>
				<tr><th>Name</th><th>Type</th><th>Phase</th><th>Collected</th></tr>
			</thead>
			<tbody>
				${artifacts.map((a) => `
				<tr>
					<td><code>${esc(a.name)}</code></td>
					<td>${esc(a.mimeType)}</td>
					<td>${a.phaseId ? esc(a.phaseId) : "—"}</td>
					<td>${formatTime(a.collectedAt)}</td>
				</tr>`).join("\n")}
			</tbody>
		</table>
	</section>`;
}

function statusIcon(status: string): string {
	switch (status) {
		case "completed": return "✓";
		case "active": return "●";
		case "failed": return "✗";
		case "skipped": return "⊘";
		case "reset": return "↺";
		default: return "○";
	}
}

function formatTime(ms: number): string {
	return new Date(ms).toISOString().replace("T", " ").replace(/\.\d+Z$/, " UTC");
}

function formatDuration(ms: number): string {
	if (ms < 1000) return `${ms}ms`;
	const secs = Math.floor(ms / 1000);
	if (secs < 60) return `${secs}s`;
	const mins = Math.floor(secs / 60);
	const remSecs = secs % 60;
	if (mins < 60) return `${mins}m ${remSecs}s`;
	const hrs = Math.floor(mins / 60);
	const remMins = mins % 60;
	return `${hrs}h ${remMins}m`;
}

function esc(s: string): string {
	return s
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

const CSS = `
:root {
	--bg: #0d1117;
	--surface: #161b22;
	--border: #30363d;
	--text: #e6edf3;
	--text-muted: #8b949e;
	--accent: #58a6ff;
	--green: #3fb950;
	--red: #f85149;
	--yellow: #d29922;
	--orange: #db6d28;
	--purple: #bc8cff;
}

@media (prefers-color-scheme: light) {
	:root {
		--bg: #ffffff;
		--surface: #f6f8fa;
		--border: #d0d7de;
		--text: #1f2328;
		--text-muted: #656d76;
		--accent: #0969da;
		--green: #1a7f37;
		--red: #cf222e;
		--yellow: #9a6700;
		--orange: #bc4c00;
		--purple: #8250df;
	}
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
	background: var(--bg);
	color: var(--text);
	line-height: 1.6;
	padding: 2rem;
}

.report {
	max-width: 900px;
	margin: 0 auto;
}

.report-header {
	margin-bottom: 2rem;
	padding-bottom: 1.5rem;
	border-bottom: 1px solid var(--border);
}

.report-header h1 {
	font-size: 1.75rem;
	font-weight: 600;
	margin-bottom: 0.75rem;
}

.meta {
	display: flex;
	flex-wrap: wrap;
	gap: 1rem;
	align-items: center;
	margin-bottom: 0.75rem;
}

.meta-item {
	color: var(--text-muted);
	font-size: 0.875rem;
}

.description {
	color: var(--text-muted);
	font-size: 0.95rem;
}

.badge {
	display: inline-block;
	padding: 0.15rem 0.6rem;
	border-radius: 2rem;
	font-size: 0.75rem;
	font-weight: 600;
	text-transform: uppercase;
	letter-spacing: 0.05em;
}

.badge-running { background: rgba(88, 166, 255, 0.15); color: var(--accent); }
.badge-completed { background: rgba(63, 185, 80, 0.15); color: var(--green); }
.badge-failed { background: rgba(248, 81, 73, 0.15); color: var(--red); }
.badge-cancelled { background: rgba(139, 148, 158, 0.15); color: var(--text-muted); }
.badge-active { background: rgba(88, 166, 255, 0.15); color: var(--accent); }
.badge-pending { background: rgba(139, 148, 158, 0.1); color: var(--text-muted); }
.badge-skipped { background: rgba(139, 148, 158, 0.1); color: var(--text-muted); }
.badge-reset { background: rgba(210, 153, 34, 0.15); color: var(--yellow); }

.badge-sm { font-size: 0.65rem; padding: 0.1rem 0.4rem; }

.context { margin-top: 1rem; }
.context h3 { font-size: 0.875rem; color: var(--text-muted); margin-bottom: 0.5rem; }
.context-table { border-collapse: collapse; font-size: 0.875rem; }
.context-table td { padding: 0.25rem 0.75rem 0.25rem 0; }
.context-key { color: var(--text-muted); font-weight: 500; }
.context-value code { background: var(--surface); padding: 0.1rem 0.4rem; border-radius: 3px; font-size: 0.85em; }

h2 {
	font-size: 1.25rem;
	font-weight: 600;
	margin-bottom: 1rem;
}

.phases {
	margin-bottom: 2rem;
}

.phase {
	background: var(--surface);
	border: 1px solid var(--border);
	border-radius: 8px;
	margin-bottom: 0.75rem;
	overflow: hidden;
}

.phase-active { border-color: var(--accent); }
.phase-completed { border-left: 3px solid var(--green); }
.phase-failed { border-left: 3px solid var(--red); }
.phase-reset { border-left: 3px solid var(--yellow); }

.phase-header {
	display: flex;
	align-items: center;
	gap: 0.75rem;
	padding: 0.75rem 1rem;
}

.phase-icon {
	font-size: 1.1rem;
	width: 1.5rem;
	text-align: center;
	flex-shrink: 0;
}

.phase-completed .phase-icon { color: var(--green); }
.phase-active .phase-icon { color: var(--accent); }
.phase-failed .phase-icon { color: var(--red); }
.phase-reset .phase-icon { color: var(--yellow); }
.phase-pending .phase-icon { color: var(--text-muted); }

.phase-title {
	font-size: 1rem;
	font-weight: 500;
	flex: 1;
}

.phase-duration {
	color: var(--text-muted);
	font-size: 0.8rem;
}

.phase-body {
	padding: 0 1rem 0.75rem 3.25rem;
}

.exit-criteria {
	font-size: 0.85rem;
	color: var(--text-muted);
}

.phase-artifacts { margin-top: 0.5rem; }
.phase-artifacts h4 { font-size: 0.8rem; color: var(--text-muted); margin-bottom: 0.25rem; }
.phase-artifacts ul { list-style: none; font-size: 0.85rem; }
.phase-artifacts li { padding: 0.1rem 0; }
.artifact-meta { color: var(--text-muted); font-size: 0.8rem; }

.artifacts { margin-bottom: 2rem; }
.artifact-table {
	width: 100%;
	border-collapse: collapse;
	font-size: 0.875rem;
}
.artifact-table th {
	text-align: left;
	padding: 0.5rem 0.75rem;
	border-bottom: 2px solid var(--border);
	color: var(--text-muted);
	font-weight: 500;
	font-size: 0.8rem;
}
.artifact-table td {
	padding: 0.5rem 0.75rem;
	border-bottom: 1px solid var(--border);
}

.report-footer {
	padding-top: 1.5rem;
	border-top: 1px solid var(--border);
	color: var(--text-muted);
	font-size: 0.8rem;
}

code {
	font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
}
`;
